services:
  #SERVER image and container
  server:
    build: ./backend
    container_name: server
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:admin@mongo:27017

  #CLIENT image and container
  client:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_WEBSITE: ${NEXT_PUBLIC_WEBSITE}
        NEXT_PUBLIC_SERVER: ${NEXT_PUBLIC_SERVER}
    container_name: client
    restart: always
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEBSITE=${NEXT_PUBLIC_WEBSITE}
      - NEXT_PUBLIC_SERVER=${NEXT_PUBLIC_SERVER}
    stdin_open: true
    tty: true

  #DATABASE image and container
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongodata: {}
