services:
  #SERVER image and container
  server:
    build: ./backend
    container_name: server
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:admin@mongo:27017

  #CLIENT image and container
  client:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_WEBSITE: http://91.99.198.196:3000
        NEXT_PUBLIC_SERVER: http://91.99.198.196:4000
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEBSITE=http://91.99.198.196:3000
      - NEXT_PUBLIC_SERVER=http://91.99.198.196:4000
    stdin_open: true
    tty: true

  #DATABASE image and container
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongodata: {}
